<#
.SYNOPSIS
    Build the SCCM-only BitDiag enterprise report script.
#>

[CmdletBinding()]
param(
    [string]$OutputPath = ".\dist\bitdiag-sccm-report.ps1"
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
$moduleRoot = Join-Path -Path $repoRoot -ChildPath "BitDiag"
$manifestPath = Join-Path -Path $moduleRoot -ChildPath "BitDiag.psd1"
$manifest = Test-ModuleManifest -Path $manifestPath
$version = [string]$manifest.Version

$outputFullPath = if ([System.IO.Path]::IsPathRooted($OutputPath)) {
    $OutputPath
} else {
    Join-Path -Path $repoRoot -ChildPath $OutputPath
}
$outputFullPath = [System.IO.Path]::GetFullPath($outputFullPath)

$outputDirectory = Split-Path -Parent $outputFullPath
if (-not (Test-Path $outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
}

$sourceFiles = @(
    "Private\00-Core.ps1"
    "Private\20-Diagnostics.Platform.ps1"
    "Private\30-Diagnostics.Disk.ps1"
    "Private\40-Diagnostics.BitLocker.ps1"
    "Private\50-Diagnostics.Policy.ps1"
    "Private\80-EnterpriseReport.ps1"
)

$lines = @(
    "<#"
    ".SYNOPSIS"
    "    SCCM-only BitDiag enterprise report collector."
    ""
    ".DESCRIPTION"
    "    Generated by build-sccm.ps1 from the modular BitDiag source tree."
    "    This script only runs diagnostics and writes the enterprise NDJSON report."
    "#>"
    ""
    "[CmdletBinding()]"
    "param("
    "    [string]`$OutDirectory,"
    ""
    "    [Alias('Drive', 'Drives')]"
    "    [string[]]`$DriveLetters,"
    ""
    "    [switch]`$AllDrives,"
    ""
    "    [switch]`$Version,"
    ""
    "    [switch]`$Quiet"
    ")"
    ""
    "`$ErrorActionPreference = 'Stop'"
    "`$script:BitDiagModuleRoot = Split-Path -Parent `$MyInvocation.MyCommand.Path"
    "`$script:BitDiagVersion = '$version'"
    ""
)

foreach ($sourceFile in $sourceFiles) {
    $sourcePath = Join-Path -Path $moduleRoot -ChildPath $sourceFile
    if (-not (Test-Path $sourcePath)) {
        throw "Missing source file: $sourcePath"
    }

    $lines += "# region $sourceFile"
    $lines += Get-Content -LiteralPath $sourcePath
    $lines += "# endregion $sourceFile"
    $lines += ""
}

$lines += @(
    "function Invoke-BitDiagSccmReport {"
    "    param("
    "        [Parameter(Mandatory = `$true)]"
    "        [string]`$OutDirectory,"
    ""
    "        [string[]]`$DriveLetters,"
    ""
    "        [switch]`$AllDrives,"
    ""
    "        [switch]`$Quiet"
    "    )"
    ""
    "    if ([string]::IsNullOrWhiteSpace(`$OutDirectory)) {"
    "        throw 'OutDirectory is required.'"
    "    }"
    ""
    "    `$driveDiscoveryResults = @()"
    "    `$driveLettersSpecified = `$null -ne `$DriveLetters -and `$DriveLetters.Count -gt 0"
    "    if (`$AllDrives -or -not `$driveLettersSpecified) {"
    "        `$detectedDrives = @(Get-DetectedDriveLetters)"
    "        `$driveDiscoveryResults = @(`$detectedDrives | Where-Object { `$_.PSObject.Properties['Category'] })"
    "        `$normalizedDriveLetters = @(`$detectedDrives | Where-Object { `$_ -is [string] })"
    ""
    "        if (-not `$normalizedDriveLetters -or `$normalizedDriveLetters.Count -eq 0) {"
    "            if (`$driveLettersSpecified) {"
    "                `$normalizedDriveLetters = ConvertTo-DriveLetter -Letters `$DriveLetters"
    "            } elseif (`$env:SystemDrive) {"
    "                `$normalizedDriveLetters = ConvertTo-DriveLetter -Letters `$env:SystemDrive"
    "            } else {"
    "                `$normalizedDriveLetters = @('C')"
    "            }"
    ""
    "            `$driveDiscoveryResults += New-CheckResult ``"
    "                -Category 'Runtime' ``"
    "                -CheckName 'Drive discovery' ``"
    "                -Status 'Warning' ``"
    "                -Message `"No drives were discovered automatically; falling back to `$(`$normalizedDriveLetters -join ', ').`" ``"
    "                -Fix 'Run as administrator or pass drive letters explicitly with -DriveLetters C.'"
    "        }"
    "    } else {"
    "        `$normalizedDriveLetters = ConvertTo-DriveLetter -Letters `$DriveLetters"
    "    }"
    ""
    "    `$bootMode = Get-BootMode"
    "    `$tpmState = Get-TpmState"
    ""
    "    `$results = @()"
    "    `$results += Test-RunningAsAdmin"
    "    `$results += `$driveDiscoveryResults"
    "    `$results += Test-BootMode -BootMode `$bootMode"
    "    `$results += Test-SecureBoot -BootMode `$bootMode"
    "    `$results += Test-Tpm -TpmState `$tpmState"
    "    `$results += Test-TpmBootCompatibility -TpmState `$tpmState -BootMode `$bootMode"
    "    `$results += Test-DiskPartitionStyle"
    "    `$results += Test-EfiSystemPartition"
    "    `$results += Test-DiskDynamic"
    "    `$results += Test-ActiveMbrPartition"
    "    `$results += Test-UnallocatedSpace"
    "    `$results += Test-BitLockerPolicy"
    ""
    "    foreach (`$driveLetter in `$normalizedDriveLetters) {"
    "        `$results += Test-FileSystem -DriveLetter `$driveLetter"
    "        `$results += Test-BitLockerVolume -DriveLetter `$driveLetter"
    "    }"
    ""
    "    `$exitCode = Get-DiagnosticsExitCode -Results `$results"
    "    `$reportPath = Export-EnterpriseReport -Results `$results -OutDirectory `$OutDirectory -ExitCode `$exitCode"
    "    if (-not `$Quiet) {"
    "        Write-Output `"Enterprise NDJSON report written to `$reportPath`""
    "    }"
    "}"
    ""
    "if (`$Version) {"
    "    Write-Output (`"bitdiag-sccm-report {0}`" -f (Get-BitDiagVersion))"
    "    return"
    "}"
    ""
    "Invoke-BitDiagSccmReport -OutDirectory `$OutDirectory -DriveLetters `$DriveLetters -AllDrives:`$AllDrives -Quiet:`$Quiet"
)

Set-Content -LiteralPath $outputFullPath -Value $lines -Encoding UTF8
Write-Host "Built $outputFullPath"
