<#
.SYNOPSIS
    Build the portable single-file BitDiag script.
#>

[CmdletBinding()]
param(
    [string]$OutputPath = ".\dist\bitdiag.ps1"
)

$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot
$moduleRoot = Join-Path -Path $repoRoot -ChildPath "BitDiag"
$manifestPath = Join-Path -Path $moduleRoot -ChildPath "BitDiag.psd1"
$manifest = Test-ModuleManifest -Path $manifestPath
$version = [string]$manifest.Version

$outputFullPath = if ([System.IO.Path]::IsPathRooted($OutputPath)) {
    $OutputPath
} else {
    Join-Path -Path $repoRoot -ChildPath $OutputPath
}
$outputFullPath = [System.IO.Path]::GetFullPath($outputFullPath)

$outputDirectory = Split-Path -Parent $outputFullPath
if (-not (Test-Path $outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
}

$sourceFiles = @(
    "Private\00-Core.ps1"
    "Private\10-Console.ps1"
    "Private\20-Diagnostics.Platform.ps1"
    "Private\30-Diagnostics.Disk.ps1"
    "Private\40-Diagnostics.BitLocker.ps1"
    "Private\50-Diagnostics.Policy.ps1"
    "Private\60-Remediation.ps1"
    "Private\70-EnableBitLocker.ps1"
    "Private\80-EnterpriseReport.ps1"
    "Private\90-Export.ps1"
    "Public\bitdiag.ps1"
)

$lines = @(
    "<#"
    ".SYNOPSIS"
    "    Portable single-file BitDiag CLI."
    ""
    ".DESCRIPTION"
    "    Generated by build.ps1 from the modular BitDiag source tree."
    "#>"
    ""
    '$script:BitDiagModuleRoot = Split-Path -Parent $MyInvocation.MyCommand.Path'
    "`$script:BitDiagVersion = '$version'"
    ""
)

foreach ($sourceFile in $sourceFiles) {
    $sourcePath = Join-Path -Path $moduleRoot -ChildPath $sourceFile
    if (-not (Test-Path $sourcePath)) {
        throw "Missing source file: $sourcePath"
    }

    $lines += "# region $sourceFile"
    $lines += Get-Content -LiteralPath $sourcePath
    $lines += "# endregion $sourceFile"
    $lines += ""
}

$lines += 'bitdiag -ExitProcess @args'

Set-Content -LiteralPath $outputFullPath -Value $lines -Encoding UTF8
Write-Host "Built $outputFullPath"
